config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :xml_columns
  resources :projects
  resources :project_columns
  resources :column_maps
  resources :xml_downloads
  resources :xmls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'



  #Projects and Project Columns Ajax Calls
  get 'project_batch_action' => 'projects#project_batch_action'
  get 'destroy_project_column' => 'project_columns#destroy'

  #XML ajax calls
  get 'xml_batch_action' => 'xmls#xml_batch_action'
  get 'destroy_xml_column' => 'xml_columns#destroy'
  get 'load_data/stores'
  get 'xml/download_xml' => 'xmls#download_xml'
  get 'xml/xml_tags' => 'xmls#xml_tags'
  get 'xml/map_xml' => 'xmls#map_xml'
  get 'load_data/parse_xml'


end

app/models/project.rb
class Project < ApplicationRecord
  #Model Relationships
  has_many :xmls
  has_many :project_columns
  has_many :memberships, :dependent => :delete_all
  
  accepts_nested_attributes_for :project_columns
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if params["project_search"]
      @projects = Project.where("name LIKE (?)","%#{params['project_search']}%")
    else
      @projects = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @columns = @project.project_columns
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project_columns = []
  end

  # GET /projects/1/edit
  def edit
    @project_columns = @project.project_columns
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        if params["project"]["new_columns"]
          params["project"]["new_columns"].each do |key, column|
            project_column = ProjectColumn.new(name: column["name"], required: column["required"])
            project_column.save
            @project.project_columns << project_column
          end
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        if params["project"]["columns"]
          params["project"]["columns"].each do |id, column_hash|
            project_column = ProjectColumn.find(id.to_i)
            project_column.update(name: column_hash["name"], required: column_hash["required"])
            project_column.required = 0 if column_hash["required"].blank?
            project_column.save
          end
        end

        if params["project"]["new_columns"]
          params["project"]["new_columns"].each do |key, column_hash|
            project_column = ProjectColumn.create(name: column_hash["name"], required: column_hash["required"])
            project_column.required = 0 if column_hash["required"].blank?
            project_column.save
            @project.project_columns << project_column
          end
        end
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Project Batch Actions
  def project_batch_action
    #Delete selected projects
    if params['batch_action'] == 'delete'
      params['projects'].each do |id|
        Project.delete(id)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :url, :api_url)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
  <%= form_for(project, html:{class: "form-horizontal"}) do |f| %>
<section class="panel panel-default">
  <header class="panel-heading font-bold">Project form</header>
  <div class="panel-body">

      <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :url, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :url, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :api_url, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :api_url, class: "form-control" %>
        </div>
      </div>
    </div>
  </section>
  <section class="panel panel-default">
    <div class="table-responsive project_columns_input_fields_wrap">
      <table class="table table-striped b-t b-light">
        <thead>
          <tr>
            <th>Column Name</th>
            <th width="30">Required</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @project_columns.each do |column| %>
            <tr>
              <td>
                <%= text_field_tag(:name, column.name, name: "project[columns][#{column.id}][name]", class: "form-control") %>
              </td>
              <td>
                <a href="#" class="project_column_required_toggle<%= column.required ? ' active' : '' %>"  data-toggle="class">
                  <i class="fa fa-check text-success text-active"></i>
                  <i class="fa fa-times text-danger text"></i>
                  <input type="hidden" name="project[columns][<%= column.id %>][required]" value="<%= column.required ? '1' : '0'%>">
                </a>
              </td>
              <td>
                <a class="project_column_destroy btn btn-default btn-xs btn-danger" rel="nofollow" href="#">Destroy<input type="hidden" value="<%= column.id %>"></a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <footer class="panel-footer">
      <div class="row">
        <div class="col-sm-6 hidden-xs">
          <button class="add_field_button btn btn-sm btn-default">Add More Columns</button>
        </div>
        <div class="col-sm-6 text-right text-center-xs">
          <%= f.submit "Update Project", class: "btn btn-s-md btn-primary" %>
        </div>
      </div>
    </footer>
  </section>
</section>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<%= link_to 'Back', projects_path, class: 'btn btn-default btn-sm btn-primary' %>
<%= link_to 'Show', @project, class: 'btn btn-default btn-sm btn-info'%>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="m-b-md">
  <h3 class="m-b-none">Projects</h3>
</div>
<section class="panel panel-default">
    <form action="/projects" method="get" id="project_batch_form">
    <div class="row wrapper">
      <div class="col-sm-5 m-b-xs">
        <select id="project_batch_action_selector" class="input-sm form-control input-s-sm inline v-middle" name="batch_action">
          <option value="0">Bulk action</option>
          <option value="delete">Delete selected</option>
        </select>
        <button type="submit" id="project_action_button" class="btn btn-sm btn-default">Apply</button>
      </div>
      <div class="col-sm-3">
        <div class="input-group">
          <input name="project_search" type="text" class="input-sm form-control" placeholder="Search">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-sm btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
      <div class="col-sm-2">
        <%= link_to 'New Project', new_project_path, class: "btn btn-sm btn-default" %>
      </div>
    </div>
    <div class="table-responsive">
    <table class="table table-striped b-t b-light">
      <thead>
        <tr>
          <th width="20"><label class="checkbox m-l m-t-none m-b-none i-checks"><input type="checkbox"><i></i></label></th>
          <th>Name</th>
          <th>Description</th>
          <th>Url</th>
          <th>Api url</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><label class="checkbox m-l m-t-none m-b-none i-checks"><input class="project_checkbox" type="checkbox" name="projects[<%=project.id%>]" value="<%= project.name %>"><i></i></label></td>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.url %></td>
            <td><%= project.api_url %></td>
            <td><%= link_to 'Show', project, class: "btn btn-xs btn-info" %></td>
            <td><%= link_to 'Edit', edit_project_path(project), class: "btn btn-xs btn-primary" %></td>
            <td><%= link_to 'Destroy', project, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </form>
</section>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= link_to 'Back', projects_path, class: 'btn btn-default btn-sm btn-primary' %>
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-default btn-sm btn-primary' %>
<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-default btn-sm btn-success' %>

<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6">
    <section class="panel panel-default">
      <header class="panel-heading">
        Project
      </header>
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <tbody>
            <tr>
              <td>Name</td>
              <td><%= @project.name %></td>
            </tr>
            <tr>
              <td>Description</td>
              <td><%= @project.description %></td>
            </tr>
            <tr>
              <td>Url</td>
              <td><%= @project.url %></td>
            </tr>
            <tr>
              <td>Api Url</td>
              <td><%= @project.api_url %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  </div>

  <div class="col-sm-6">
    <section class="panel panel-default">
      <header class="panel-heading">
        Columns
      </header>
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th>Name</th>
              <th width="30">Required</th>
            </tr>
          </thead>
          <tbody>
            <% @columns.each do |column|%>
              <tr>
                <td><%= column.name %></td>
                <td>
                  <% if column.required %>
                    <a class="active">
                      <i class="fa fa-check text-success text-active"></i>
                    </a>
                  <% else %>
                    <i class="fa fa-times text-danger text"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>