config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :xml_columns
  resources :projects
  resources :project_columns
  resources :column_maps
  resources :xml_downloads
  resources :xmls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'



  #Projects and Project Columns Ajax Calls
  get 'project_batch_action' => 'projects#project_batch_action'
  get 'destroy_project_column' => 'project_columns#destroy'

  #XML ajax calls
  get 'xml_batch_action' => 'xmls#xml_batch_action'
  get 'destroy_xml_column' => 'xml_columns#destroy'
  get 'load_data/stores'
  get 'xml/download_xml' => 'xmls#download_xml'
  get 'xml/xml_tags' => 'xmls#xml_tags'
  get 'xml/map_xml' => 'xmls#map_xml'
  get 'load_data/parse_xml'


end

app/models/xml.rb
class Xml < ApplicationRecord
  #Model Relationships
  belongs_to :project
  has_many :xml_downloads
  has_many :xml_columns
  #has_many :memberships, :dependent => :delete_all

  #Parse XML file
  def parse_xml
    @observation_hash = {success: 0, fail: 0, total: 0}
    xml_download = self.download
    if xml_download.is_a_new_xml
      self.increase_version
      xml_download.parsing!
      entries = []
      data = Nokogiri::XML::Reader(File.open(xml_download.path))
      data.each do |node|
        if(node.name == self.main_tag && node.node_type == Nokogiri::XML::Reader::TYPE_ELEMENT)
          begin
            entry = self.parse_columns(Nokogiri::XML(node.outer_xml))
            entries << entry unless entry.blank?
            if entries.length >= 100
              #self.save_entries self.project.api_url, entries
              entries = []
            end
          rescue Exception => e
            @observation_hash[:fail] += 1
            xml_download.update_column(:xml_errors, e.message)
            puts "error #{e.message}"
            puts Nokogiri::XML(node.outer_xml)
          end
        end
      end
      xml_download.observations = ""
      @observation_hash.each do |key,value|
        xml_download.observations += "#{key}: #{value}. "
      end
      xml_download.done!
    end
  end

  #Parse each XML column for an entry
  def parse_columns unparsed_entry
    entry = {}
    required_columns = []
    @observation_hash[:total] += 1
    self.project.project_columns.includes(:xml_columns).each do |column|
      related_xml_column = column.xml_columns.first
      unless related_xml_column.blank?
        #Content inside xml tag
        column_value = unparsed_entry.xpath("//#{related_xml_column.name}")[0].inner_text
        regex = Regexp.new related_xml_column.regex
        column_value = Xml::apply_column_regex column_value, regex
        column_value = Xml::number_fix column_value if related_xml_column.number_fix
        entry[column.name] = column_value
        required_columns << column.name.to_sym if column.required
      end
    end
    if required_columns.all? {|c| entry[c].present?}
      @observation_hash[:success] += 1
      return entry
    else
      @observation_hash[:fail] += 1
      puts "Not all required columns filled"
      return nil
    end
  end

  #Download XML file from URL
  def download
    FileUtils.mkdir_p("tmp/xmls") unless File.directory?("tmp/xmls")
    xml_download = XmlDownload.create(xml_id: self.id)
    #XmlDownloadWorker.perform_async(xml_download.id, self.id)
    #File Download
    begin
      uri = URI.parse(self.url)
      file_path = Rails.root.join('tmp','xmls',self.id.to_s+'_xml_'+DateTime.now.to_i.to_s+'.xml')
      xml_download.path = file_path.to_s
      Net::HTTP.start(uri.host) do |http|
        begin
          xml_download.downloading!
          response = http.request_head(self.url)
          xml_download.file_size = response['content-length']
          file = open(file_path, 'wb')
          http.request_get(uri.request_uri) do |response|
            response.read_body do |segment|
              file.write(segment)
            end
          end
        ensure
          file.close
        end
      end
    rescue Exception => e
      xml_download.xml_errors = e.to_s
      xml_download.interrupted!
      raise e
      return false
    end
    return xml_download
  end

  #Test url without having to save a XML model first
  def self.test_url url
    Xml.new(url: url).download
  end

  #XML Version increment
  def increase_version
    self.version = self.version.nil? ? 1 : self.version + 1
    self.save
  end

  def self.number_fix number
    number.gsub("BRL","").strip.to_f
  end

  def self.apply_column_regex string, regex
    return regex.match string unless regex.blank?
  end

end

app/controllers/xmls_controller.rb
class XmlsController < ApplicationController
  before_action :set_xml, only: [:download_xml,:show, :edit, :update, :destroy]
  layout false, :only => [:xml_tags, :map_xml]

  # GET /xmls
  # GET /xmls.json
  def index
    #if params["xml_search"]
    #  @xmls = Xml.where("url LIKE (?)","%#{params['xml_search']}%")
    #else
      @xmls = Xml.all
    #end
  end

  # GET /xmls/1
  # GET /xmls/1.json
  def show
    @columns = @xml.xml_columns
  end

  # GET /xmls/new
  def new
    @xml = Xml.new
  end

  # GET /xmls/1/edit
  def edit
  end

  # POST /xmls
  # POST /xmls.json
  def create
    @xml = Xml.new(xml_params)

    respond_to do |format|
      if @xml.save
        format.html { redirect_to @xml, notice: 'Xml was successfully created.' }
        format.json { render :show, status: :created, location: @xml }
      else
        format.html { render :new }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xmls/1
  # PATCH/PUT /xmls/1.json
  def update
    respond_to do |format|
      if @xml.update(xml_params)
        format.html { redirect_to @xml, notice: 'Xml was successfully updated.' }
        format.json { render :show, status: :ok, location: @xml }
      else
        format.html { render :edit }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xmls/1
  # DELETE /xmls/1.json
  def destroy
    @xml.destroy
    respond_to do |format|
      format.html { redirect_to xmls_url, notice: 'Xml was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def download_xml

    @xml.download

    sample = @xml.xml_downloads.first.first_chars
    xml_download_path = @xml.xml_downloads.last.path
    respond_to do |format|
      format.html { render plain: sample }
      format.json { render status: :ok, location: @xml}
    end
  end

  def xml_tags
    @xml = Xml.find(params[:xml][:id])
    @tags = XmlDownload.xml_tags(@xml.xml_downloads.last.path, params[:xml][:main_tag])
##    pp tags
##    respond_to do |format|
##      format.json { render :json => tags }
##    end
  end

  def map_xml
    @xml= Xml.find(params["id"])
    @project_columns = @xml.project.project_columns unless @xml.blank? || @xml.project.blank?
    @xml_columns = @xml.xml_columns unless @xml.blank? || @xml.xml_columns.blank?
    #if(@project_columns)
    #  @project_columns_required = @project_columns.where("required = ?",true)
    #  @project_columns_not_required = @project_columns.where("required = ?",false)
    #end
  end

  #XML Batch Actions
  def xml_batch_action
    #Delete selected xmls
    if params['batch_action'] == 'delete'
      params['xml'].each do |id|
        Xml.delete(id)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xml
      @xml = Xml.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xml_params
      params.require(:xml).permit(:url, :store_id, :version, :remove_namespaces, :encoding, :main_tag, :custom_fields, :validated, :project_id,:store_name)
    end
end

app/helpers/xmls_helper.rb
module XmlsHelper
end

app/views/xmls/_form.html.erb
<%= form_for(xml) do |f| %>
  <% if xml.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xml.errors.count, "error") %> prohibited this xml from being saved:</h2>

      <ul>
      <% xml.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :id, :value => xml.id%>
  </div>

  <div class="field">
    <%= f.label :project_id , :class => "form_label"%>
    <%= f.select :project_id, Project.all.map{|p|[p.name, p.id]} %>
  </div>

  <div class="field">
    <%= f.label :url, :class => "form_label"%>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :store_id, :class => "form_label" %>
    <%= f.select :store_id,""%>
    <%= f.hidden_field :store_name%>
  </div>

  <div class="field">
    <%= f.label "Sample", :class => "form_label" %>
    <textarea rows="20" cols="100" id="sample_text" name="sample[text]" disabled= true hidden= true></textarea>
  </div>

  <div class="field">
    <%= f.label :main_tag, :class => "form_label" %>
    <%= f.text_field :main_tag, :disabled => true, :hidden => true %>
  </div>
  <div class="field" id="check_box">

  </div>
  <div class="field" id="list_box">

  </div>

  <div class="actions">
    <%= submit_tag "Test XML", :id => "test_xml", :type => "button", :disabled => true %>
    <%= submit_tag "Download XML", :id => "download_xml", :type => "button", :disabled => true %>
    <%= submit_tag "Set Main Tag", :id => "set_main_tag", :type => "button", :disabled => true, :hidden =>true %>
    <%= submit_tag "Map Tags", :id => "map_tags", :type => "button", :disabled => true, :hidden =>true %>
    <%= submit_tag "Parse XML", :id => "parse_xml", :type => "button", :disabled => true, :hidden =>true %>
  </div>


<% end %>

app/views/xmls/edit.html.erb
<h1>Editing Xml</h1>

<%= render 'form', xml: @xml %>

<%= link_to 'Show', @xml %> |
<%= link_to 'Back', xmls_path %>

app/views/xmls/index.html.erb
<p id="notice"><%= notice %></p>

<div class="m-b-md">
  <h3 class="m-b-none">XMLs</h3>
</div>
<section class="panel panel-default">
  <form action="/xmls" method="get" id="xml_batch_form">
  <div class="row wrapper">
    <div class="col-sm-5 m-b-xs">
      <select id="xml_batch_action_selector" class="input-sm form-control input-s-sm inline v-middle" name="batch_action">
        <option value="0">Bulk action</option>
        <option value="delete">Delete selected</option>
      </select>
      <button type="submit" id="xml_action_button" class="btn btn-sm btn-default">Apply</button>
    </div>
    <div class="col-sm-3">
      <div class="input-group">
        <input name="xml_search" type="text" class="input-sm form-control" placeholder="Search">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-sm btn-default" type="button">Go!</button>
        </span>
      </div>
    </div>
    <div class="col-sm-2">
      <%= link_to 'New XML', new_xml_path, class: "btn btn-sm btn-default" %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
      <thead>
        <tr>
          <th width="20"><label class="checkbox m-l m-t-none m-b-none i-checks"><input type="checkbox"><i></i></label></th>
          <th>Url</th>
          <th>Store</th>
          <th>Version</th>
          <th>Validated</th>
          <th>Project</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @xmls.each do |xml| %>
          <tr>
            <td><label class="checkbox m-l m-t-none m-b-none i-checks"><input class="xmls_checkbox" type="checkbox" name="xml[<%=xml.id%>]" value="<%= xml.url %>"><i></i></label></td>
            <td><%= xml.url %></td>
            <td><%= xml.store_name %></td>
            <td><%= xml.version %></td>
            <td><%= xml.validated %></td>
            <td><%= xml.project_id %></td>
            <td><%= link_to 'Show', xml, class: "btn btn-xs btn-info" %></td>
            <td><%= link_to 'Edit', edit_xml_path(xml), class: "btn btn-xs btn-primary" %></td>
            <td><%= link_to 'Destroy', xml, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</form>
</section>

app/views/xmls/map_xml.html.erb
<% @project_columns.each do |t| %>
  <% column_map = ColumnMap.new(project_column_id: t.id) %>

  <%= render partial: "column_maps/form_ajax", locals: {column_map: column_map, xml_columns: @xml_columns, xml:  @xml}  %>
<% end %>
<script>
$('form[data-remote=true]').on("submit", function(e){
    e.preventDefault();
    $.rails.handleRemote($(this));
    $(this).hide();
});
</script>

app/views/xmls/new.html.erb
<h1>New Xml</h1>

<%= render 'form', xml: @xml %>

<%= link_to 'Back', xmls_path %>

app/views/xmls/show.html.erb
<%= link_to 'Back', xmls_path, class: 'btn btn-default btn-sm btn-primary' %>
<%= link_to 'Edit', edit_xml_path(@xml), class: 'btn btn-default btn-sm btn-success' %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-8">
    <section class="panel panel-default">
      <header class="panel-heading">
        XML
      </header>
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <tbody>
            <tr>
              <td>Url</td>
              <td><%= @xml.url %></td>
            </tr>
            <tr>
              <td>Store</td>
              <td><%= @xml.store_name %></td>
            </tr>
            <tr>
              <td>XML Version</td>
              <td><%= @xml.version %></td>
            </tr>
            <tr>
              <td>Remove Namespaces</td>
              <td><%= @xml.remove_namespaces %></td>
            </tr>
            <tr>
              <td>Encoding</td>
              <td><%= @xml.encoding %></td>
            </tr>
            <tr>
              <td>Main Tag</td>
              <td><%= @xml.main_tag %></td>
            </tr>
            <tr>
              <td>Custom Fields</td>
              <td><%= @xml.custom_fields %></td>
            </tr>
            <tr>
              <td>Validated</td>
              <td><%= @xml.validated %></td>
            </tr>
            <tr>
              <td>Project Id</td>
              <td><%= @xml.project_id %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  </div>
  <div class="col-sm-4">
    <section class="panel panel-default">
      <header class="panel-heading">
        Columns
      </header>
      <div class="table-responsive">
        <table class="table table-striped b-t b-light">
          <thead>
            <tr>
              <th>Name</th>
              <th>Number Fix</th>
              <th>Regex</th>
            </tr>
          </thead>
          <tbody>
            <% @columns.each do |column|%>
              <tr>
                <td><%= column.name %></td>
                <td><%= column.number_fix %></td>
                <td><%= column.regex %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
  </div>

</div>

app/views/xmls/xml_tags.html.erb
<% @tags.each do |t| %>
  <% xml_column = XmlColumn.new(name: t, xml_id: @xml.id) %>

  <%= render partial: "xml_columns/form_ajax", locals: {xml_column: xml_column}  %>
<% end %>
<script>
$('form[data-remote=true]').on("submit", function(e){
    e.preventDefault();
    $.rails.handleRemote($(this));
    $(this).hide();
});
</script>