config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :xml_columns
  resources :projects
  resources :project_columns
  resources :column_maps
  resources :xml_downloads
  resources :xmls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'



  #Projects and Project Columns Ajax Calls
  get 'project_batch_action' => 'projects#project_batch_action'
  get 'destroy_project_column' => 'project_columns#destroy'

  #XML ajax calls
  get 'xml_batch_action' => 'xmls#xml_batch_action'
  get 'destroy_xml_column' => 'xml_columns#destroy'
  get 'load_data/stores'
  get 'xml/download_xml' => 'xmls#download_xml'
  get 'xml/xml_tags' => 'xmls#xml_tags'
  get 'xml/map_xml' => 'xmls#map_xml'
  get 'load_data/parse_xml'


end

app/models/xml_column.rb
class XmlColumn < ApplicationRecord
  belongs_to :xml
  has_many :column_maps
  has_many :project_columns, through: :column_maps
  has_many :memberships, :dependent => :delete_all
end

app/controllers/xml_columns_controller.rb
class XmlColumnsController < ApplicationController
  before_action :set_xml_column, only: [:show, :edit, :update, :destroy]

  # GET /xml_columns
  # GET /xml_columns.json
  def index
    @xml_columns = XmlColumn.all
  end

  # GET /xml_columns/1
  # GET /xml_columns/1.json
  def show
  end

  # GET /xml_columns/new
  def new
    @xml_column = XmlColumn.new
  end

  # GET /xml_columns/1/edit
  def edit
  end

  # POST /xml_columns
  # POST /xml_columns.json
  def create
    @xml_column = XmlColumn.new(xml_column_params)

    respond_to do |format|
      if @xml_column.save
        format.html { redirect_to @xml_column, notice: 'Xml column was successfully created.' }
        format.json { render :show, status: :created, location: @xml_column }
        format.js
      else
        format.html { render :new }
        format.json { render json: @xml_column.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /xml_columns/1
  # PATCH/PUT /xml_columns/1.json
  def update
    respond_to do |format|
      if @xml_column.update(xml_column_params)
        format.html { redirect_to @xml_column, notice: 'Xml column was successfully updated.' }
        format.json { render :show, status: :ok, location: @xml_column }
      else
        format.html { render :edit }
        format.json { render json: @xml_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xml_columns/1
  # DELETE /xml_columns/1.json
  def destroy
    @xml_column.destroy
    respond_to do |format|
      format.html { redirect_to xml_columns_url, notice: 'Xml column was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xml_column
      @xml_column = XmlColumn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xml_column_params
      params.require(:xml_column).permit(:name, :xml_id, :regex, :number_fix)
    end
end

app/helpers/xml_columns_helper.rb
module XmlColumnsHelper
end

app/views/xml_columns/_form.html.erb
<%= form_for(xml_column) do |f| %>
  <% if xml_column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xml_column.errors.count, "error") %> prohibited this xml_column from being saved:</h2>

      <ul>
      <% xml_column.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :xml_id %>
    <%= f.number_field :xml_id %>
  </div>

  <div class="field">
    <%= f.label :regex %>
    <%= f.text_field :regex %>
  </div>

  <div class="field">
    <%= f.label :number_fix %>
    <%= f.check_box :number_fix %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xml_columns/_form_ajax.html.erb
<%= form_for(xml_column, remote: true, format: :js) do |f| %>
  <% if xml_column.errors.any? %>
    <div id="error_explanation" style="display: inline">
      <h2><%= pluralize(xml_column.errors.count, "error") %> prohibited this xml_column from being saved:</h2>

      <ul>
      <% xml_column.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: inline">
    <h6><%= xml_column.name %></h6>
    <%= f.hidden_field :name %>
  </div>

  <div class="field" style="display: inline">
    <%= f.hidden_field :xml_id %>
  </div>

  <div class="field" style="display: inline">
    <%= f.label :regex %>:
    <%= f.text_field :regex %>
  </div>

  <div class="field" style="display: inline">
    <%= f.label :number_fix %>? :
    <%= f.check_box :number_fix %>
  </div>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <div class="actions" style="display: inline">
    <%= f.submit %>
  </div>
<% end %>

app/views/xml_columns/create.js.erb
$(this).hide();

app/views/xml_columns/edit.html.erb
<h1>Editing Xml Column</h1>

<%= render 'form', xml_column: @xml_column %>

<%= link_to 'Show', @xml_column %> |
<%= link_to 'Back', xml_columns_path %>

app/views/xml_columns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xml Columns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Xml</th>
      <th>Regex</th>
      <th>Number fix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xml_columns.each do |xml_column| %>
      <tr>
        <td><%= xml_column.name %></td>
        <td><%= xml_column.xml_id %></td>
        <td><%= xml_column.regex %></td>
        <td><%= xml_column.number_fix %></td>
        <td><%= link_to 'Show', xml_column %></td>
        <td><%= link_to 'Edit', edit_xml_column_path(xml_column) %></td>
        <td><%= link_to 'Destroy', xml_column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xml Column', new_xml_column_path %>

app/views/xml_columns/new.html.erb
<h1>New Xml Column</h1>

<%= render 'form', xml_column: @xml_column %>

<%= link_to 'Back', xml_columns_path %>

app/views/xml_columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @xml_column.name %>
</p>

<p>
  <strong>Xml:</strong>
  <%= @xml_column.xml_id %>
</p>

<p>
  <strong>Regex:</strong>
  <%= @xml_column.regex %>
</p>

<p>
  <strong>Number fix:</strong>
  <%= @xml_column.number_fix %>
</p>

<%= link_to 'Edit', edit_xml_column_path(@xml_column) %> |
<%= link_to 'Back', xml_columns_path %>