config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :xml_columns
  resources :projects
  resources :project_columns
  resources :column_maps
  resources :xml_downloads
  resources :xmls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'



  #Projects and Project Columns Ajax Calls
  get 'project_batch_action' => 'projects#project_batch_action'
  get 'destroy_project_column' => 'project_columns#destroy'

  #XML ajax calls
  get 'xml_batch_action' => 'xmls#xml_batch_action'
  get 'destroy_xml_column' => 'xml_columns#destroy'
  get 'load_data/stores'
  get 'xml/download_xml' => 'xmls#download_xml'
  get 'xml/xml_tags' => 'xmls#xml_tags'
  get 'xml/map_xml' => 'xmls#map_xml'
  get 'load_data/parse_xml'


end

app/models/xml_download.rb
class XmlDownload < ApplicationRecord

  require "nokogiri"
  #Model Relationships
  belongs_to :xml
  #status values
  enum status: [ :downloading, :parsing, :done, :interrupted ]

  #Verify if XML file is the same
  def is_a_new_xml
    last_xml_download = XmlDownload.where(xml_id: self.xml_id).order(id: :desc).second
    if last_xml_download.blank?
      self.file_md5 = Digest::MD5.file self.path
      self.parsing!
      return true
    end
    self.file_md5 = Digest::MD5.file self.path
    if last_xml_download.file_md5 == self.file_md5
      File.delete(self.path) if File.exist?(self.path)
      self.observations = "XML file hasn't changed"
      self.done!
      return false
    else
      self.parsing!
      return true
    end
  end

  def first_chars
    if (f = File.open(self.path))
      return f.read(3000)
    else
      return nil
    end
  end

  def self.xml_tags(path, main_tag)
    tags = []
    xml_path = path
    main ="//#{main_tag}"
    @doc = Nokogiri::XML(File.read(xml_path))
    products = @doc.xpath("//#{main}").take(100).each do |tag|
      tag.children.each do |node|
        tags << node.name unless tags.include? node.name
      end
     end
     return tags
  end

end

app/controllers/xml_downloads_controller.rb
class XmlDownloadsController < ApplicationController
  before_action :set_xml_download, only: [:show, :edit, :update, :destroy]

  # GET /xml_downloads
  # GET /xml_downloads.json
  def index
    @xml_downloads = XmlDownload.all
  end

  # GET /xml_downloads/1
  # GET /xml_downloads/1.json
  def show
  end

  # GET /xml_downloads/new
  def new
    @xml_download = XmlDownload.new
  end

  # GET /xml_downloads/1/edit
  def edit
  end

  # POST /xml_downloads
  # POST /xml_downloads.json
  def create
    @xml_download = XmlDownload.new(xml_download_params)

    respond_to do |format|
      if @xml_download.save
        format.html { redirect_to @xml_download, notice: 'Xml download was successfully created.' }
        format.json { render :show, status: :created, location: @xml_download }
      else
        format.html { render :new }
        format.json { render json: @xml_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xml_downloads/1
  # PATCH/PUT /xml_downloads/1.json
  def update
    respond_to do |format|
      if @xml_download.update(xml_download_params)
        format.html { redirect_to @xml_download, notice: 'Xml download was successfully updated.' }
        format.json { render :show, status: :ok, location: @xml_download }
      else
        format.html { render :edit }
        format.json { render json: @xml_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xml_downloads/1
  # DELETE /xml_downloads/1.json
  def destroy
    @xml_download.destroy
    respond_to do |format|
      format.html { redirect_to xml_downloads_url, notice: 'Xml download was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xml_download
      @xml_download = XmlDownload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xml_download_params
      params.require(:xml_download).permit(:xml_id, :status, :test, :xml_errors, :path, :observations, :file_size)
    end
end

app/helpers/xml_downloads_helper.rb
module XmlDownloadsHelper
end

app/views/xml_downloads/_form.html.erb
<%= form_for(xml_download) do |f| %>
  <% if xml_download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xml_download.errors.count, "error") %> prohibited this xml_download from being saved:</h2>

      <ul>
      <% xml_download.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xml_id %>
    <%= f.number_field :xml_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :test %>
    <%= f.check_box :test %>
  </div>

  <div class="field">
    <%= f.label :xml_errors %>
    <%= f.text_area :xml_errors %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="field">
    <%= f.label :observations %>
    <%= f.text_area :observations %>
  </div>

  <div class="field">
    <%= f.label :file_size %>
    <%= f.number_field :file_size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xml_downloads/edit.html.erb
<h1>Editing Xml Download</h1>

<%= render 'form', xml_download: @xml_download %>

<%= link_to 'Show', @xml_download %> |
<%= link_to 'Back', xml_downloads_path %>

app/views/xml_downloads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xml Downloads</h1>

<table>
  <thead>
    <tr>
      <th>Xml</th>
      <th>Status</th>
      <th>Test</th>
      <th>Xml errors</th>
      <th>Path</th>
      <th>Observations</th>
      <th>File size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xml_downloads.each do |xml_download| %>
      <tr>
        <td><%= xml_download.xml_id %></td>
        <td><%= xml_download.status %></td>
        <td><%= xml_download.test %></td>
        <td><%= xml_download.xml_errors %></td>
        <td><%= xml_download.path %></td>
        <td><%= xml_download.observations %></td>
        <td><%= xml_download.file_size %></td>
        <td><%= link_to 'Show', xml_download %></td>
        <td><%= link_to 'Edit', edit_xml_download_path(xml_download) %></td>
        <td><%= link_to 'Destroy', xml_download, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xml Download', new_xml_download_path %>

app/views/xml_downloads/new.html.erb
<h1>New Xml Download</h1>

<%= render 'form', xml_download: @xml_download %>

<%= link_to 'Back', xml_downloads_path %>

app/views/xml_downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xml:</strong>
  <%= @xml_download.xml_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @xml_download.status %>
</p>

<p>
  <strong>Test:</strong>
  <%= @xml_download.test %>
</p>

<p>
  <strong>Xml errors:</strong>
  <%= @xml_download.xml_errors %>
</p>

<p>
  <strong>Path:</strong>
  <%= @xml_download.path %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @xml_download.observations %>
</p>

<p>
  <strong>File size:</strong>
  <%= @xml_download.file_size %>
</p>

<%= link_to 'Edit', edit_xml_download_path(@xml_download) %> |
<%= link_to 'Back', xml_downloads_path %>